# @package _global_

name: download_bilibili_video
mode: mcp
activated_tools: null
mcp_transport: stdio
mcp_client_session_timeout_seconds: 20
config:
  command: .venv/bin/python
  args: ["main.py"]
  cwd: configs/tools/generated/download_bilibili_video